import { Router } from "express";
import * as repo from "../services/repository.js";
import { requireStudentOrTeacher } from "../services/auth.service.js";

const router = Router();

// No PII accepted or returned — nickname and avatarId are the only personalization.
// Also never returns pinHash (see auth.service.js): responses are built from an
// explicit allowlist rather than passing the stored record straight through, since
// the in-memory store (unlike the select:false Mongo schema) has no field hiding.
function toPublicStudent(student) {
  if (!student) return null;
  return { studentId: student.studentId, nickname: student.nickname, avatarId: student.avatarId, createdAt: student.createdAt };
}

// studentId is normally generated by the CLIENT (so a brand-new profile works with
// zero connectivity) and just registered here; if none is supplied, the server
// generates one instead, for any other caller of this API.
router.post("/", async (req, res, next) => {
  try {
    const { studentId, nickname, avatarId } = req.body ?? {};
    if (studentId) {
      const existing = await repo.getStudent(studentId);
      if (existing) return res.status(200).json(toPublicStudent(existing));
      const student = { studentId, nickname: nickname || "Explorer", avatarId: avatarId || "fox", createdAt: new Date().toISOString() };
      await repo.upsertStudentRecord(student);
      return res.status(201).json(toPublicStudent(student));
    }
    const student = await repo.createStudent({ nickname, avatarId });
    res.status(201).json(toPublicStudent(student));
  } catch (err) {
    next(err);
  }
});

router.get("/:id", requireStudentOrTeacher, async (req, res, next) => {
  try {
    const student = await repo.getStudent(req.params.id);
    if (!student) return res.status(404).json({ error: "Student not found" });
    res.json(toPublicStudent(student));
  } catch (err) {
    next(err);
  }
});

export default router;
